# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.network "forwarded_port", guest: 8888, host: 8888

  config.vm.synced_folder "..", "/telegraf-input-lotus"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    
    vb.cpus = 4
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
  end
end
